In [13]:
import numpy as np
import math

In [14]:
#Sigmoid Function
def sigmoid(x):
  activation = 1/(1 + np.exp(-x))
  return activation

In [15]:
act = sigmoid(np.array([1,2,3]))
print(act)

[0.73105858 0.88079708 0.95257413]


In [16]:
#Hyperbolic Tanh Function
def Tanh(x):
  activation = ((np.exp(x) - np.exp(-x))/(np.exp(x) + np.exp(-x))); 
  return activation

In [17]:
act = Tanh(np.array([1,2,3]))
print(act)

[0.76159416 0.96402758 0.99505475]


In [18]:
#Softmax Function
def Softmax(x):
  exp = np.exp(x)
  activation = exp/exp.sum()
  return activation 

In [19]:
act = Softmax(np.array([3.0,1.0,0.2]))
print(act)

[0.8360188  0.11314284 0.05083836]


In [20]:
#RELU Function
def RELU(X):
   return np.maximum(0,X)

In [21]:
act = RELU(np.array([-1,2,3]))
print(act)

[0 2 3]
